-- +goose Up
-- +goose StatementBegin

-- Stable POI identity.
--
-- The problem: POIs surfaced by search were generated by the LLM and given a
-- fresh uuid.New() on every call, then never persisted. The same place came back
-- with a different id each search, GetPOI 500'd for all of them, and every table
-- keyed on poi_id (reviews, saved_pois, list_items, itinerary_pois,
-- user_favorite_pois) could not attach to anything a user could actually see.
-- Saving or reviewing a place you found was impossible.
--
-- The fix has two halves. This migration provides the identity: one row per real
-- place, enforced by the database. The service layer then resolves generated POIs
-- against it instead of inventing ids.
--
-- The dedupe key is (city, normalised name, coordinates rounded to 3dp ≈ 110m).
-- Name alone is wrong — a city can hold several "Café Central" — and raw
-- coordinates are wrong too, because the LLM returns slightly different decimals
-- for the same place on different calls. Together they are stable enough to
-- match re-generations while still separating genuinely distinct places.

-- Step 1: merge any pre-existing duplicates so the unique index below can be
-- created. This is a no-op on a clean database. It keeps the OLDEST row of each
-- group (the one other data is most likely already pointing at) and repoints
-- dependants at it before deleting the rest.
CREATE TEMPORARY TABLE poi_dupe_map AS
WITH keyed AS (
    SELECT
        id,
        city_id,
        lower(btrim(name)) AS norm_name,
        round(ST_Y(location)::numeric, 3) AS lat3,
        round(ST_X(location)::numeric, 3) AS lon3,
        created_at,
        row_number() OVER (
            PARTITION BY city_id, lower(btrim(name)),
                         round(ST_Y(location)::numeric, 3),
                         round(ST_X(location)::numeric, 3)
            ORDER BY created_at ASC, id ASC
        ) AS rn,
        first_value(id) OVER (
            PARTITION BY city_id, lower(btrim(name)),
                         round(ST_Y(location)::numeric, 3),
                         round(ST_X(location)::numeric, 3)
            ORDER BY created_at ASC, id ASC
        ) AS keep_id
    FROM points_of_interest
)
SELECT id AS dupe_id, keep_id
FROM keyed
WHERE rn > 1;

-- Repoint dependants. The DO NOTHING variants matter: several of these tables
-- carry a UNIQUE (user_id, poi_id), so merging two POIs a user had both saved
-- would otherwise collide.
UPDATE reviews r SET poi_id = m.keep_id
FROM poi_dupe_map m WHERE r.poi_id = m.dupe_id;

DELETE FROM saved_pois s
USING poi_dupe_map m
WHERE s.poi_id = m.dupe_id
  AND EXISTS (SELECT 1 FROM saved_pois k WHERE k.user_id = s.user_id AND k.poi_id = m.keep_id);
UPDATE saved_pois s SET poi_id = m.keep_id
FROM poi_dupe_map m WHERE s.poi_id = m.dupe_id;

DELETE FROM user_favorite_pois f
USING poi_dupe_map m
WHERE f.poi_id = m.dupe_id
  AND EXISTS (SELECT 1 FROM user_favorite_pois k WHERE k.user_id = f.user_id AND k.poi_id = m.keep_id);
UPDATE user_favorite_pois f SET poi_id = m.keep_id
FROM poi_dupe_map m WHERE f.poi_id = m.dupe_id;

UPDATE list_items li SET poi_id = m.keep_id
FROM poi_dupe_map m WHERE li.poi_id = m.dupe_id;

UPDATE itinerary_pois ip SET poi_id = m.keep_id
FROM poi_dupe_map m WHERE ip.poi_id = m.dupe_id;

DELETE FROM points_of_interest p USING poi_dupe_map m WHERE p.id = m.dupe_id;

DROP TABLE poi_dupe_map;

-- Step 2: enforce it. From here the database itself guarantees one row per place,
-- which is what makes ON CONFLICT upserts in the service layer safe under
-- concurrent searches.
--
-- city_id is nullable, and NULLs are never equal in a unique index, so POIs
-- without a city are not deduped by this. That is deliberate: without a city we
-- cannot tell "Central Park" in one place from another.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_poi_city_name_location
    ON points_of_interest (
        city_id,
        lower(btrim(name)),
        round(ST_Y(location)::numeric, 3),
        round(ST_X(location)::numeric, 3)
    );

-- Supports the resolve-before-insert lookup on the search path.
CREATE INDEX IF NOT EXISTS idx_poi_city_norm_name
    ON points_of_interest (city_id, lower(btrim(name)));

-- +goose StatementEnd
