-- +goose Up
-- +goose StatementBegin

-- Durable cache of LLM generations, one row per (cache key) = one part of one
-- answer: the city summary, the general POI list, the itinerary, the hotel /
-- restaurant / activity lists.
--
-- Why a plain table and not llm_interactions: that table is a TimescaleDB
-- hypertable (migration 0044) with a 14-day compression policy and a 90-day
-- retention policy. A cache row has to survive as long as its TTL says, has to
-- be looked up by an exact key (a unique index on a hypertable must include the
-- partitioning column, so `cache_key` alone cannot be the primary key there),
-- and has to be updated in place on every hit (compressed chunks reject
-- UPDATE). None of that fits a time-partitioned audit log, so the reusable
-- artefact lives here and llm_interactions keeps one row per request saying
-- what was shown and where it came from.
--
-- No foreign keys: the row is keyed by content, not by who asked, and carrying
-- a reference into the hypertable would block chunk maintenance (see 0071).
--
-- Derived state. Safe to truncate: every row can be regenerated by paying the
-- provider call it saved.

CREATE TABLE IF NOT EXISTS llm_generations (
    -- "gen:" + sha256 over the template version, part, domain, city, model,
    -- language, normalised query and profile snapshot (plus user / rounded
    -- location for the personal and location-bound parts). Built in the chat
    -- service; the columns below repeat the human-readable inputs so a row can
    -- be explained without recomputing the hash.
    cache_key TEXT PRIMARY KEY CHECK (cache_key <> ''),

    -- Bumped whenever a prompt template changes; old rows stop matching
    -- because the version is inside the key, and this column lets a purge
    -- find them.
    template_version TEXT NOT NULL DEFAULT '',

    -- city_data | general_pois | itinerary | hotels | restaurants | activities
    part TEXT NOT NULL CHECK (part <> ''),
    domain TEXT NOT NULL DEFAULT '',

    -- model_id is what the router planned to use (it is inside the key);
    -- model_version is what the provider answered with (it is not).
    model_id TEXT NOT NULL DEFAULT '',
    model_version TEXT NOT NULL DEFAULT '',

    -- sha256 of the rendered prompt, for drift checks between key and prompt.
    prompt_hash TEXT NOT NULL DEFAULT '',

    -- Normalised city name, and the resolved city id when the city was known
    -- at generation time. Both nullable-in-spirit: a purge after a bulk POI
    -- ingest goes by name, so the name is what is indexed.
    city TEXT NOT NULL DEFAULT '',
    city_id UUID NULL,

    -- The raw model output for this part, as it would have been streamed.
    -- Empty output is never a valid cache entry.
    response TEXT NOT NULL CHECK (response <> ''),

    -- The evidence packet the answer was grounded on ('ungrounded' when none).
    -- Not part of the key on purpose: evidence staleness is bounded by
    -- expires_at, and this column keeps the audit trail honest.
    packet_id TEXT NOT NULL DEFAULT 'ungrounded',

    tokens_in INT NOT NULL DEFAULT 0,
    tokens_out INT NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,

    hit_count INT NOT NULL DEFAULT 0,
    last_hit_at TIMESTAMPTZ NULL
);

-- The daily sweep: DELETE ... WHERE expires_at <= NOW().
CREATE INDEX IF NOT EXISTS idx_llm_generations_expires_at
    ON llm_generations (expires_at);

-- The admin purge after a bulk POI ingest: DELETE ... WHERE city = $1.
CREATE INDEX IF NOT EXISTS idx_llm_generations_city
    ON llm_generations (city);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS llm_generations;
-- +goose StatementEnd
