-- +goose Up
-- +goose StatementBegin

-- City Packs: pre-made itineraries, written offline and published by hand.
--
-- These are the first rows in this database that are *product* rather than a
-- record of what a user did. That changes two things.
--
-- First, the content cannot be allowed to rot. Everything needed to render a
-- stop is copied onto bundle_stops at authoring time; points_of_interest is an
-- enrichment link, not a dependency. See the comment on bundle_stops.poi_id.
--
-- Second, once someone has paid, the row has to outlive every editorial
-- decision that follows. A pack is withdrawn by moving it to 'retired', never
-- by deleting it, and bundle_purchases.bundle_id is RESTRICT so the database
-- refuses to let that happen by accident.
--
-- Price is deliberately absent. Every pack costs the same today, so the amount
-- lives in configuration next to the Stripe price id it has to agree with. A
-- number duplicated here would eventually disagree with the one the customer
-- is actually charged.
CREATE TABLE IF NOT EXISTS bundles (
    id           UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
    -- The URL and the SEO key. Stable across re-generations of the content.
    slug         TEXT NOT NULL UNIQUE CHECK (slug <> ''),
    title        TEXT NOT NULL CHECK (title <> ''),
    summary      TEXT NOT NULL DEFAULT '',

    -- City by id *and* by name. The name is what renders; the id is how the
    -- pack joins to weather, map centring and everything else. 0068 merges
    -- places by name within a city, and cities themselves can be rewritten by
    -- the resolver, so the pack keeps its own copy of what it is about.
    city_id      UUID REFERENCES cities (id) ON DELETE SET NULL,
    city_name    TEXT NOT NULL CHECK (city_name <> ''),
    country_code TEXT NOT NULL DEFAULT '' CHECK (char_length(country_code) <= 2),

    -- The taste the pack is cut for, and the months it is in season.
    -- months mirrors SeasonalPick.months in the client, which is where the
    -- seed list for generation comes from.
    theme        TEXT NOT NULL DEFAULT '',
    months       SMALLINT[] NOT NULL DEFAULT '{}',

    day_count    INT NOT NULL DEFAULT 0 CHECK (day_count >= 0),
    stop_count   INT NOT NULL DEFAULT 0 CHECK (stop_count >= 0),
    cover_image_url TEXT,

    -- Whether the days past the first cost money. The amount does not live
    -- here; see the note above.
    is_paid      BOOLEAN NOT NULL DEFAULT FALSE,

    -- draft -> approved -> published -> retired. Only 'published' is ever
    -- visible to a client; 'retired' stays readable by whoever bought it.
    status       TEXT NOT NULL DEFAULT 'draft'
                 CHECK (status IN ('draft', 'approved', 'published', 'retired')),

    -- Provenance. A pack is generated by a model and published by a person, so
    -- any later complaint can be traced back to both.
    source_prompt TEXT NOT NULL DEFAULT '',
    source_model  TEXT NOT NULL DEFAULT '',
    generated_at  TIMESTAMPTZ,
    approved_by   TEXT NOT NULL DEFAULT '',
    approved_at   TIMESTAMPTZ,
    published_at  TIMESTAMPTZ,
    -- When the content was last checked against reality. Rendered on the page:
    -- opening hours and prices drift, and saying when we last looked is the
    -- honest version of a guarantee we cannot make.
    verified_at   TIMESTAMPTZ,

    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bundles_published
    ON bundles (published_at DESC) WHERE status = 'published';
CREATE INDEX IF NOT EXISTS idx_bundles_months ON bundles USING GIN (months);
CREATE INDEX IF NOT EXISTS idx_bundles_theme ON bundles (theme);
CREATE INDEX IF NOT EXISTS idx_bundles_city_id ON bundles (city_id);

CREATE TRIGGER trigger_set_bundles_updated_at
BEFORE UPDATE ON bundles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS bundle_days (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
    bundle_id   UUID NOT NULL REFERENCES bundles (id) ON DELETE CASCADE,
    day_number  INT  NOT NULL CHECK (day_number >= 1),
    title       TEXT NOT NULL DEFAULT '',
    summary     TEXT NOT NULL DEFAULT '',
    CONSTRAINT unique_bundle_day UNIQUE (bundle_id, day_number)
);

CREATE INDEX IF NOT EXISTS idx_bundle_days_bundle ON bundle_days (bundle_id, day_number);

-- One stop in a pack.
--
-- Every column from name downwards is a SNAPSHOT taken when the pack was
-- authored, not a projection of points_of_interest. The read path renders from
-- these columns and treats the POI row as optional extra detail.
--
-- That is not redundancy for its own sake. 0067 and 0068 establish that POI
-- identity is (city, normalised name) and that duplicates get MERGED: the
-- oldest row wins, dependants are repointed and the rest are deleted. Those
-- migrations repoint dependants by hand-enumerating the tables that reference
-- poi_id.
--
--   ==> ANY FUTURE POI-MERGE MIGRATION MUST ADD bundle_stops TO THAT LIST. <==
--
-- If it does not, ON DELETE SET NULL below turns a merge into a null pointer
-- rather than a wrong one, and the snapshot means the customer still sees the
-- pack they paid for. Losing the link costs enrichment; it cannot cost content.
CREATE TABLE IF NOT EXISTS bundle_stops (
    id               UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
    bundle_day_id    UUID NOT NULL REFERENCES bundle_days (id) ON DELETE CASCADE,
    order_index      INT  NOT NULL DEFAULT 0 CHECK (order_index >= 0),

    poi_id           UUID REFERENCES points_of_interest (id) ON DELETE SET NULL,

    name             TEXT NOT NULL CHECK (name <> ''),
    category         TEXT NOT NULL DEFAULT '',
    description      TEXT NOT NULL DEFAULT '',
    latitude         DOUBLE PRECISION,
    longitude        DOUBLE PRECISION,
    address          TEXT NOT NULL DEFAULT '',
    website          TEXT,
    booking_url      TEXT,
    image_url        TEXT,
    -- Why this stop is here, in the pack's own voice.
    notes            TEXT NOT NULL DEFAULT '',
    start_minute     INT CHECK (start_minute BETWEEN 0 AND 1440),
    duration_minutes INT CHECK (duration_minutes >= 0),

    CONSTRAINT unique_bundle_stop_order UNIQUE (bundle_day_id, order_index)
);

CREATE INDEX IF NOT EXISTS idx_bundle_stops_day ON bundle_stops (bundle_day_id, order_index);
CREATE INDEX IF NOT EXISTS idx_bundle_stops_poi ON bundle_stops (poi_id) WHERE poi_id IS NOT NULL;

-- Who owns what.
--
-- Ownership is a row in this table and nothing else. It is never inferred from
-- a subscription: a pack is a separate purchase, not a Pro benefit, and a Pro
-- subscriber who has not bought a pack does not have it. PRICING.md:90.
--
-- bundle_id is RESTRICT, not CASCADE. Deleting a pack someone paid for should
-- fail loudly rather than quietly erase what they bought.
CREATE TABLE IF NOT EXISTS bundle_purchases (
    id                        UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
    user_id                   UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    bundle_id                 UUID NOT NULL REFERENCES bundles (id) ON DELETE RESTRICT,

    -- The second idempotency gate. webhook_events already makes a replayed
    -- delivery a no-op; this makes a duplicate grant impossible even if the
    -- same purchase arrives down a different path (a reconcile sweep, say).
    stripe_checkout_session_id TEXT NOT NULL UNIQUE CHECK (stripe_checkout_session_id <> ''),
    stripe_payment_intent_id   TEXT NOT NULL DEFAULT '',

    amount_cents              INT  NOT NULL CHECK (amount_cents >= 0),
    currency                  TEXT NOT NULL DEFAULT 'usd',
    status                    TEXT NOT NULL DEFAULT 'paid'
                              CHECK (status IN ('paid', 'refunded')),

    purchased_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    refunded_at               TIMESTAMPTZ
);

-- One live entitlement per user per pack. Partial, so a refunded row does not
-- block buying it again later.
CREATE UNIQUE INDEX IF NOT EXISTS bundle_purchases_active
    ON bundle_purchases (user_id, bundle_id) WHERE status = 'paid';

CREATE INDEX IF NOT EXISTS idx_bundle_purchases_user ON bundle_purchases (user_id);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS bundle_purchases;
DROP TABLE IF EXISTS bundle_stops;
DROP TABLE IF EXISTS bundle_days;
DROP TRIGGER IF EXISTS trigger_set_bundles_updated_at ON bundles;
DROP TABLE IF EXISTS bundles;
-- +goose StatementEnd
