package service

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/google/uuid"
	"google.golang.org/genai"

	"github.com/FACorreiaa/loci-connect-api/internal/types"
	"github.com/FACorreiaa/loci-connect-api/pkg/observability"
)

// ErrGastronomyCityNotFound is returned when a city id does not name a known
// city.
var ErrGastronomyCityNotFound = errors.New("city not found")

// ErrGastronomyUnavailable is returned when the model produced nothing usable
// for the city — usually because the name is not a real place.
var ErrGastronomyUnavailable = errors.New("no gastronomy available for this city")

// GetCityGastronomy returns a city's typical gastronomy for the standalone
// lookup. It lives on the chat service because it is the same generation as
// the chat pipeline's gastronomy part: the same prompt, the same parser, the
// same model routing and the same cache key (gastronomyCacheKey), so a city
// generated by either path is served to both.
//
// Exactly one of cityID and cityName is expected. A name that is not in the
// cities table is still answered, keyed by its normalised name, the way the
// chat pipeline answers a city it has not seen before.
func (l *ServiceImpl) GetCityGastronomy(ctx context.Context, cityID uuid.UUID, cityName string) (*locitypes.CityGastronomy, bool, error) {
	cityName = strings.TrimSpace(cityName)
	switch {
	case cityID != uuid.Nil:
		if l.cityRepo == nil {
			return nil, false, ErrGastronomyCityNotFound
		}
		city, err := l.cityRepo.GetCityByID(ctx, cityID)
		if err != nil {
			return nil, false, fmt.Errorf("get city: %w", err)
		}
		if city == nil {
			return nil, false, ErrGastronomyCityNotFound
		}
		cityName = city.Name
	case cityName != "":
		cityID = l.resolveCityID(ctx, cityName)
	default:
		return nil, false, ErrGastronomyCityNotFound
	}

	modelID := l.modelFor(ctx)
	key := gastronomyCacheKey(cityID, cityName, modelID)
	name := string(partGastronomy)

	if g, ok := l.cachedGastronomy(ctx, key); ok {
		return g, true, nil
	}

	release, err := l.acquireLLMSlot(ctx)
	if err != nil {
		return nil, false, fmt.Errorf("LLM capacity exceeded: %w", err)
	}
	defer release()

	prompt := getGastronomyPrompt(cityName)
	response, err := l.aiClient.Generate(ctx, prompt, &genai.GenerateContentConfig{
		Temperature:     genai.Ptr[float32](defaultTemperature),
		MaxOutputTokens: outputTokenBudget(gastronomyPlaceBudget),
	})
	if err != nil {
		return nil, false, fmt.Errorf("generate gastronomy: %w", err)
	}

	var text strings.Builder
	var modelVersion string
	var tokensIn, tokensOut int
	if response != nil {
		modelVersion = response.ModelVersion
		if u := response.UsageMetadata; u != nil {
			tokensIn, tokensOut = int(u.PromptTokenCount), int(u.CandidatesTokenCount)
		}
		for _, cand := range response.Candidates {
			if cand.Content == nil {
				continue
			}
			for _, part := range cand.Content.Parts {
				text.WriteString(part.Text)
			}
		}
	}
	raw := text.String()

	g, err := parseGastronomy(raw)
	if err != nil || !g.Usable() {
		observability.RecordLLMCacheLookup(name,
			observability.LLMCacheLayerNone, observability.LLMCacheResultInvalid)
		l.logger.WarnContext(ctx, "gastronomy generation unusable",
			slog.String("city_name", cityName), slog.Any("error", err))
		return nil, false, ErrGastronomyUnavailable
	}
	if g.CityName == "" {
		g.CityName = cityName
	}

	l.storeGastronomy(ctx, locitypes.LLMGeneration{
		CacheKey:        key,
		TemplateVersion: generationTemplateVersion,
		Part:            name,
		ModelID:         modelID,
		ModelVersion:    modelVersion,
		PromptHash:      promptHash(prompt),
		City:            normalizeCacheComponent(cityName),
		CityID:          cityIDPtr(cityID),
		Response:        raw,
		TokensIn:        tokensIn,
		TokensOut:       tokensOut,
		ExpiresAt:       time.Now().Add(partTTL(partGastronomy)),
	})
	return g, false, nil
}

// cachedGastronomy reads the gastronomy under key from memory, then from the
// durable table, the same order lookupGenerations uses. A durable hit is
// mirrored into memory. Anything unreadable is a miss.
func (l *ServiceImpl) cachedGastronomy(ctx context.Context, key string) (*locitypes.CityGastronomy, bool) {
	name := string(partGastronomy)
	if text, ok := l.cachedText(key); ok {
		if g, err := parseGastronomy(text); err == nil && g.Usable() {
			observability.RecordLLMCacheLookup(name,
				observability.LLMCacheLayerMemory, observability.LLMCacheResultHit)
			return g, true
		}
	}
	if l.generations == nil {
		observability.RecordLLMCacheLookup(name,
			observability.LLMCacheLayerNone, observability.LLMCacheResultMiss)
		return nil, false
	}
	row, err := l.generations.GetGeneration(ctx, key)
	if err != nil {
		l.logger.WarnContext(ctx, "durable gastronomy lookup failed", slog.Any("error", err))
	}
	if err != nil || row == nil || row.Response == "" || !row.ExpiresAt.After(time.Now()) {
		observability.RecordLLMCacheLookup(name,
			observability.LLMCacheLayerDB, observability.LLMCacheResultMiss)
		return nil, false
	}
	g, err := parseGastronomy(row.Response)
	if err != nil || !g.Usable() {
		return nil, false
	}
	if ttl := memoryGenerationTTL(partTTL(partGastronomy), row.ExpiresAt); ttl > 0 && l.cache != nil {
		l.cache.Set(key, row.Response, ttl)
	}
	observability.RecordLLMCacheLookup(name,
		observability.LLMCacheLayerDB, observability.LLMCacheResultHit)
	return g, true
}

// storeGastronomy writes a validated generation to both cache layers. Failures
// are logged and swallowed: a cache that cannot be filled is slow, not broken.
func (l *ServiceImpl) storeGastronomy(ctx context.Context, row locitypes.LLMGeneration) {
	ttl := partTTL(partGastronomy)
	if l.cache != nil {
		l.cache.Set(row.CacheKey, row.Response, min(ttl, maxMemoryGenerationTTL))
	}
	if l.generations == nil {
		return
	}
	if err := l.generations.PutGeneration(ctx, row); err != nil {
		l.logger.WarnContext(ctx, "failed to store gastronomy generation", slog.Any("error", err))
	}
}

func cityIDPtr(id uuid.UUID) *uuid.UUID {
	if id == uuid.Nil {
		return nil
	}
	return &id
}
